TODOAPP/urls.py
from django.urls import path
from .views import HomePageView,TaskCreateView,TaskDetailView, TaskDeleteView, TaskSearchView, TaskUpdateView

urlpatterns = [
   path('', HomePageView.as_view(),name='home'),
   path('new/', TaskCreateView.as_view(),name='newtask'),
   path('<int:pk>/',TaskDetailView.as_view(),name='task_detail'),
   path('<int:pk>/delete/',TaskDeleteView.as_view(),name='task_delete'),
   path('search/',TaskSearchView.as_view(),name='search'),
   path('<pk>/update', TaskUpdateView.as_view(), name='update'),

]

TODOPROJECT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('TODOAPP.urls')),
    path('admin/', admin.site.urls),
]

TODOAPP/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    task= models.CharField(max_length=150)
    task_description = models.TextField()

def __str__(self):
    return self.task

TODOAPP/views.py
from django.shortcuts import render
from .models import Item
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

# Create your views here.

class HomePageView(ListView):
    model=Item
    template_name='TODOAPP/home.html'

class TaskCreateView(CreateView):
    model=Item
    template_name='TODOAPP/createtask.html'
    fields=["task","task_description"]
    success_url= reverse_lazy('home')

class TaskDetailView(DetailView):
    model= Item
    template_name='TODOAPP/taskdescription.html'

class TaskDeleteView(DeleteView):
    model = Item
    template_name='TODOAPP/delete.html'
    success_url = reverse_lazy('home')

class TaskSearchView(ListView):
    model = Item
    template_name= 'TODOAPP/home.html'
    queryset= Item.objects.all()

    def get_queryset(self):
        result = self.request.GET.get('search_term')
        return Item.objects.filter(task__icontains =result)

class TaskUpdateView(UpdateView):
    model=Item
    template_name='TODOAPP/update.html'
    fields=["task","task_description"]
    success_url= reverse_lazy('home')

TODOAPP/templates/TODOAPP/createtask.html
{% extends 'TODOAPP/home.html' %}
{% block content%}
    <h3>New Task</h3>
        <form action="" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="save">
        </form>
{% endblock content%}

TODOAPP/templates/TODOAPP/delete.html
{% extends 'TODOAPP/home.html' %}
{% block content%}

<div class="container">

  <form action="" method="post">
      {%csrf_token%}
      <p> Are you sure you want to delete "{{item.task}}" ?</p>
      <button class="btn btn-danger ml-2" type="submit"> Confirm </button>


  </form>
</div>



{% endblock content%}

TODOAPP/templates/TODOAPP/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>TO DO APP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style type="text/css" media="screen">
    body {
  background-color: #ebf218;
}
        ul{
            List-Style-type:none;
            margin:0;
            padding:0;
            overflow:hidden;
            background-color:blue;
            }

          li{
               float:left;
               color:white;
               font-size:30px;
               font-family:serif;



               }

           li a{
                display:block;
                color:white;
                text-align:center;
                padding:14px 16px;
                text-decoration:none;

                }

             .active{
                       background-color:yellow;
                       }
              li a:hover{
              background-color:pink;
              }
              table, th,td {
              border:1px solid;
              border-color: black;
              border-collapse:collapse;
              padding:15px
              }

            a{
            text-decoration: none;
            }

            form{
            padding:50px;
            }
        </style>

    <div class="container">
        <ul>
            <li>
                <a href="{%url 'home' %}" title="">HOME</a>
            </li>
            <li style="padding: 14px 16px;margin-left:300px;">  TO DO LIST </li>
            <li style="float:right">
                <a href="{% url 'newtask'%}" title="">+ADD NEW TASK</a>
            </li>
        </ul>

    </div>

    <div class="container">
        <form action="{% url 'search' %}" method="get">
            {%csrf_token%}
            <input type="text" name="search_term" placeholder="Search here!">
            <button type="submit"> Search </button>

        </form>
    </div>
</head>
<body>
    {%block content %}
       <div class="container">
          {% for item in item_list %}
            <table style="width:100%">
                <tr>
                    <td style="width:600%"><a href="{%url 'task_detail' item.pk %}" title="">{{item.task}}</a> </td>
                    <td style="width:20%"><a href="{%url 'task_delete' item.pk %}" title="" style="color: #ff6666"> DELETE </a> </td>
                    <td style="width:20%"><a href="{%url 'update' item.pk %}" title="" style="color: #ff6666"> EDIT </a> </td>

                </tr>
            </table>

            {%endfor%}
       </div>

    {%endblock content %}
</body>
</html>

TODOAPP/templates/TODOAPP/taskdescription.html
{% extends 'TODOAPP/home.html' %}
{% block content%}

    <div class="container">
      <h4>{{item.task}}</h4>
      <p>{{item.task_description}}</p>

    </div>

{% endblock content%}

TODOAPP/templates/TODOAPP/update.html
{% extends 'TODOAPP/home.html' %}
{% block content%}
    <h3>Update Task</h3>
        <form action="" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="update">
        </form>
{% endblock content%}